const $=id=>document.getElementById(id);const qsa=s=>[...document.querySelectorAll(s)];
const state={health:null,rows:[]};
function toast(msg){let e=$('toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3200)}
function filters(){return {year:$('filterYear').value,quarter:$('filterQuarter').value,month:$('filterMonth').value,district:$('filterDistrict').value,alarm:$('filterAlarm').value}}
function query(obj){let p=new URLSearchParams;Object.entries(obj).forEach(([k,v])=>{if(v&&!['TODOS','TODAS'].includes(v))p.set(k,v)});return p.toString()}
async function api(path){let r=await fetch(path);let j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||`HTTP ${r.status}`);return j}
function moduleView(name){qsa('.nav').forEach(b=>b.classList.toggle('active',b.dataset.module===name));qsa('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));if(name==='control')loadControl();if(name==='expedientes')loadCases()}
qsa('.nav').forEach(b=>b.onclick=()=>moduleView(b.dataset.module));
async function health(){try{let h=await api('/api/health');state.health=h;$('serverDot').className='dot ok';$('serverState').textContent='Servidor conectado';$('serverDetail').textContent=h.version;$('dataPath').textContent=h.data_dir||'—'}catch(e){$('serverDot').className='dot bad';$('serverState').textContent='Servidor no disponible';$('serverDetail').textContent=e.message}}
function barChart(id,data){let box=$(id),entries=Object.entries(data||{}).sort((a,b)=>b[1]-a[1]);let max=Math.max(1,...entries.map(x=>x[1]));box.innerHTML=entries.length?entries.map(([k,v])=>`<div class="bar"><i style="height:${Math.max(4,Math.round(v/max*120))}px"></i><b>${Number(v).toLocaleString('es-CR')}</b><small title="${k}">${k}</small></div>`).join(''):'<small>Sin datos para el filtro.</small>'}
function alarmPill(a){return `<span class="pill ${a}">${a==='red'?'🔴 Roja':a==='yellow'?'🟡 Amarilla':'🟢 Verde'}</span>`}
async function loadDashboard(){try{let f=filters(),qs=query(f),d=await api('/api/dashboard?'+qs),m=await api('/api/movements?limit=80&'+qs);$('kMov').textContent=d.movimientos.toLocaleString('es-CR');$('kFolios').textContent=d.folios.toLocaleString('es-CR');$('kRed').textContent=d.alarmas.red||0;$('kYellow').textContent=d.alarmas.yellow||0;$('kDistricts').textContent=Object.keys(d.por_distrito||{}).length;$('ctxPending').textContent=d.folios;$('ctxRed').textContent=d.alarmas.red||0;$('ctxYellow').textContent=d.alarmas.yellow||0;$('ctxGreen').textContent=d.alarmas.green||0;$('ctxYear').textContent=f.year;$('ctxQuarter').textContent=f.quarter;$('ctxMonth').textContent=f.month;$('ctxDistrict').textContent=f.district;$('dashboardScope').textContent=[f.year,f.quarter,f.month,f.district,f.alarm].join(' · ');barChart('districtBars',d.por_distrito);barChart('sourceBars',d.por_fuente);state.rows=m.rows;$('recentRows').innerHTML=m.rows.slice(0,30).map(r=>`<tr><td><b>${r.folio||'—'}</b></td><td>${r.distrito}</td><td>${r.fecha||'—'}</td><td>${r.fuente}</td><td>${r.codigo||'—'}</td><td>${r.operacion||'—'}</td><td>${alarmPill(r.alarma)}</td></tr>`).join('');await loadImports()}catch(e){toast(e.message)}}
async function loadImports(){try{let r=await api('/api/imports');let by={};r.rows.forEach(x=>{let y=x.anio||'—';(by[y]??=new Set).add(x.trimestre)});$('quarterHistory').innerHTML=Object.entries(by).slice(0,4).map(([y,s])=>`<div><b>${y}</b> · ${['T1','T2','T3','T4'].map(q=>s.has(q)?q+' ✓':q+' ○').join(' · ')}</div>`).join('')||'Sin cargas registradas.'}catch(e){$('quarterHistory').textContent='Sin historial.'}}
async function loadControl(){try{let r=await api('/api/movements?limit=500&'+query(filters())),term=$('controlSearch').value.toLowerCase();let rows=r.rows.filter(x=>!term||[x.folio,x.titular,x.cedula,x.codigo,x.operacion].some(v=>String(v||'').toLowerCase().includes(term)));$('controlRows').innerHTML=rows.map(x=>`<tr><td><b>${x.folio||'—'}</b></td><td>${x.derecho||'—'}</td><td>${x.plano||'—'}</td><td>${x.fecha||'—'}</td><td>${x.distrito}</td><td>${x.codigo||'—'}</td><td>${x.operacion||'—'}</td><td>${x.titular||'—'}</td><td>${alarmPill(x.alarma)}</td></tr>`).join('')}catch(e){toast(e.message)}}
function uploadOne(file,year,quarter,district,index,total){return new Promise((resolve,reject)=>{let x=new XMLHttpRequest,url=`/api/upload?${query({year,quarter,district})}`;x.open('POST',url);x.setRequestHeader('Content-Type','application/octet-stream');x.setRequestHeader('X-Filename',file.name);x.upload.onprogress=e=>{if(e.lengthComputable){let overall=((index+e.loaded/e.total)/total)*100;$('uploadProgress').style.width=overall+'%';$('importStatus').textContent=`Subiendo ${file.name} · ${Math.round(e.loaded/e.total*100)}%`}};x.onload=()=>{try{let j=JSON.parse(x.responseText);if(x.status>=400||j.ok===false)reject(new Error(j.error||'Error'));else resolve(j)}catch(e){reject(e)}};x.onerror=()=>reject(new Error('Fallo de conexión durante la carga'));x.send(file)})}
async function importFiles(){let files=[...$('importFiles').files];if(!files.length)return toast('Seleccione uno o más archivos.');files.sort((a,b)=>(!a.name.toUpperCase().includes('CATALOGO_COD_'))-(!b.name.toUpperCase().includes('CATALOGO_COD_')));let y=$('importYear').value,q=$('importQuarter').value,d=$('importDistrict').value,total=0;try{for(let i=0;i<files.length;i++){let r=await uploadOne(files[i],y,q,d,i,files.length);total+=r.inserted||0}$('uploadProgress').style.width='100%';$('importStatus').textContent=`Carga completada · ${total.toLocaleString('es-CR')} registros nuevos`;toast('Importación completada');await loadDashboard()}catch(e){$('importStatus').textContent='ERROR · '+e.message;toast(e.message)}}
async function loadCases(){try{let r=await api('/api/cases?search='+encodeURIComponent($('caseSearch').value));$('caseList').innerHTML=r.rows.map(c=>`<article class="panel case"><b>${c.folio||'Sin folio'}</b><div>${c.distrito}</div><small>${c.status}</small><p>${c.note||'Sin nota'}</p></article>`).join('')||'<article class="panel">Sin expedientes.</article>'}catch(e){toast(e.message)}}
async function createCase(){let body={folio:$('caseFolio').value,district:$('caseDistrict').value,note:$('caseNote').value};let r=await fetch('/api/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok||j.ok===false)return toast(j.error||'Error');$('caseFolio').value='';$('caseNote').value='';loadCases()}
function doExport(kind){location.href='/api/export/'+kind+'?'+query(filters())}
$('applyFilters').onclick=loadDashboard;$('refreshDashboard').onclick=loadDashboard;$('controlRefresh').onclick=loadControl;$('importButton').onclick=importFiles;$('caseSearchBtn').onclick=loadCases;$('caseCreate').onclick=createCase;$('healthBtn').onclick=health;qsa('[data-export]').forEach(b=>b.onclick=()=>doExport(b.dataset.export));
health();loadDashboard();
